INSERT INTO Equipo (nombreEquipo, ciudad, nomEstadio, anoFundacion, categoria)
VALUES
    ('Real Madrid', 'Madrid', 'Santiago Bernabeu', 1902, 0),
    ('Barcelona', 'Barcelona', 'Camp Nou', 1899, 0),
    ('Atletico de Madrid', 'Madrid', 'Wanda Metropolitano', 1903, 0),
    ('Valencia', 'Valencia', 'Mestalla', 1919, 0),
    ('Sevilla', 'Sevilla', 'Ramon Sanchez Pizjuan', 1905, 0),
    ('Villareal', 'Villareal', 'Estadio de la Ceramica', 1923, 0),
    ('Real Sociedad', 'San Sebastian', 'Anoeta', 1909, 0),
    ('Betis', 'Sevilla', 'Benito Villamarin', 1907, 0),
    ('Athletic Club', 'Bilbao', 'San Mames', 1898, 0),
    ('Espanyol', 'Barcelona', 'RCDE Stadium', 1900, 0),
    ('Celta de Vigo', 'Vigo', 'Balaidos', 1923, 0),
    ('Getafe', 'Getafe', 'Coliseum Alfonso Perez', 1946, 0),
    ('Eibar', 'Eibar', 'Ipurua', 1940, 0),
    ('Alaves', 'Vitoria', 'Mendizorroza', 1921, 0),
    ('Levante', 'Valencia', 'Ciutat de Valencia', 1909, 0),
    ('Leganes', 'Leganes', 'Butarque', 1928, 0),
    ('Real Valladolid', 'Valladolid', 'Jose Zorrilla', 1928, 0),
    ('Rayo Vallecano', 'Madrid', 'Vallecas', 1924, 0),
    ('Girona', 'Girona', 'Montilivi', 1930, 0),
    ('Huesca', 'Huesca', 'El Alcoraz', 1960, 0),
    ('Osasuna', 'Pamplona', 'El Sadar', 1920, 0),
    ('Malaga', 'Malaga', 'La Rosaleda', 1941, 0),
    ('Cadiz', 'Cadiz', 'Ramon de Carranza', 1910, 0);
